# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 企鹅阅读

on:
  workflow_dispatch:
  schedule:
    - cron: '*/11 * * * *'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        COOKIE_QQYD1: ${{ secrets.COOKIE_QQYD1 }}
        COOKIE_QQYD2: ${{ secrets.COOKIE_QQYD2 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install got download tough-cookie
      - name: ' 运行 【企鹅阅读一】'
        if: env.COOKIE_QQYD1
        run: |
          node qqyd.js
        env:
          COOKIE_QQYD: ${{ secrets.COOKIE_QQYD1 }}
      - name: ' 运行 【企鹅阅读二】'
        if: env.COOKIE_QQYD2
        run: |
          node qqyd.js
        env:
          COOKIE_QQYD: ${{ secrets.COOKIE_QQYD2 }}
