# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 企鹅读书-lxk0301

on:
  workflow_dispatch:
  schedule:
     - cron: '*/11 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQREAD_BODY: ${{ secrets.QQ_READ_HEADER_VAL }}
        QQREAD_TIMEURL: ${{ secrets.QQ_READ_TIME_URL_VAL }}
        QQREAD_TIMEHD: ${{ secrets.QQ_READ_TIME_HEADER_VAL }}
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/yysy/qqreader.git ~/qqreader
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.QQREAD_TIMEHD
        run: |
          cd ~/qqreader
          npm install
      - name: '运行 【企鹅读书】'
        if: env.QQREAD_TIMEHD
        run: |
          cd ~/qqreader
          node qqreads--lxk0301.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

